/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import ElementBoardMoving from "./Components/Controller/Elements/ElementBoardMoving"
import ElementStar from "./Components/Controller/Elements/ElementStar"
import FightScene from "./Components/Controller/Scenes/FightScene"
import CheckpointAdventureScene from "./Components/Controller/Scenes/CheckpointAdventureScene"
import ElementBoardDraw from "./Components/Controller/Elements/ElementBoardDraw"
import ElementGroundThorn from "./Components/Controller/Elements/ElementGroundThorn"
import ElementsSavePos from "./Components/Controller/Elements/ElementsSavePos"
import ElementDoor from "./Components/Controller/Elements/ElementDoor"
import ElementDoorKey from "./Components/Controller/Elements/ElementDoorKey"
import ElementWind from "./Components/Controller/Elements/ElementWind"
import BattleScene from "./Components/Controller/Scenes/BattleScene"
import CheckpointKindScene from "./Components/Controller/Scenes/CheckpointKindScene"
import CheckpointSelectScene from "./Components/Controller/Scenes/CheckpointSelectScene"
import ElementManager from "./Components/Controller/Elements/ElementManager"
import FightSceneAdjuster from "./Components/Controller/Scenes/FightSceneAdjuster"
import LoadScene from "./Components/Controller/Scenes/LoadScene"
import DataCenter from "./GlobalData/DataCenter"
import MainScene from "./Components/Controller/Scenes/MainScene"
import ElementAchievement from "./Components/Controller/user_action/Elements/ElementAchievement"
import Achievement from "./Components/Controller/user_action/Achievement"
import BackpackScene from "./Components/Controller/user_action/BackpackScene"
import RankingScene from "./Components/Controller/user_action/RankingScene"
import ElementCommodity from "./Components/Controller/user_action/Elements/ElementCommodity"
import StoreScene from "./Components/Controller/user_action/StoreScene"
import CheckpointUI from "./Components/Controller/Pages/CheckpointUI"
import DeadPageUI from "./Components/Controller/Pages/DeadPageUI"
import ExtraAttrPageUI from "./Components/Controller/Pages/ExtraAttrPageUI"
import FightInfoUI from "./Components/Controller/Pages/FightInfoUI"
import FinishPageUI from "./Components/Controller/Pages/FinishPageUI"
import MapPageUI from "./Components/Controller/Pages/MapPageUI"
import PausePageUI from "./Components/Controller/Pages/PausePageUI"
import Player from "./Components/Controller/Scenes/Player"
import TreasureBoxPage from "./Components/Controller/Pages/TreasureBoxPage"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1280;
    static height:number=720;
    static scaleMode:string="showall";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="user_action/BackpackScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Components/Controller/Elements/ElementBoardMoving.ts",ElementBoardMoving);
        reg("Components/Controller/Elements/ElementStar.ts",ElementStar);
        reg("Components/Controller/Scenes/FightScene.ts",FightScene);
        reg("Components/Controller/Scenes/CheckpointAdventureScene.ts",CheckpointAdventureScene);
        reg("Components/Controller/Elements/ElementBoardDraw.ts",ElementBoardDraw);
        reg("Components/Controller/Elements/ElementGroundThorn.ts",ElementGroundThorn);
        reg("Components/Controller/Elements/ElementsSavePos.ts",ElementsSavePos);
        reg("Components/Controller/Elements/ElementDoor.ts",ElementDoor);
        reg("Components/Controller/Elements/ElementDoorKey.ts",ElementDoorKey);
        reg("Components/Controller/Elements/ElementWind.ts",ElementWind);
        reg("Components/Controller/Scenes/BattleScene.ts",BattleScene);
        reg("Components/Controller/Scenes/CheckpointKindScene.ts",CheckpointKindScene);
        reg("Components/Controller/Scenes/CheckpointSelectScene.ts",CheckpointSelectScene);
        reg("Components/Controller/Elements/ElementManager.ts",ElementManager);
        reg("Components/Controller/Scenes/FightSceneAdjuster.ts",FightSceneAdjuster);
        reg("Components/Controller/Scenes/LoadScene.ts",LoadScene);
        reg("GlobalData/DataCenter.ts",DataCenter);
        reg("Components/Controller/Scenes/MainScene.ts",MainScene);
        reg("Components/Controller/user_action/Elements/ElementAchievement.ts",ElementAchievement);
        reg("Components/Controller/user_action/Achievement.ts",Achievement);
        reg("Components/Controller/user_action/BackpackScene.ts",BackpackScene);
        reg("Components/Controller/user_action/RankingScene.ts",RankingScene);
        reg("Components/Controller/user_action/Elements/ElementCommodity.ts",ElementCommodity);
        reg("Components/Controller/user_action/StoreScene.ts",StoreScene);
        reg("Components/Controller/Pages/CheckpointUI.ts",CheckpointUI);
        reg("Components/Controller/Pages/DeadPageUI.ts",DeadPageUI);
        reg("Components/Controller/Pages/ExtraAttrPageUI.ts",ExtraAttrPageUI);
        reg("Components/Controller/Pages/FightInfoUI.ts",FightInfoUI);
        reg("Components/Controller/Pages/FinishPageUI.ts",FinishPageUI);
        reg("Components/Controller/Pages/MapPageUI.ts",MapPageUI);
        reg("Components/Controller/Pages/PausePageUI.ts",PausePageUI);
        reg("Components/Controller/Scenes/Player.ts",Player);
        reg("Components/Controller/Pages/TreasureBoxPage.ts",TreasureBoxPage);
    }
}
GameConfig.init();